### ISSUE TITLE
communication between RP2040 and ESP8285 unreliable

### ISSUE THREAD

**Issue by Hermann-SW** [IsQianGe/rp2040-spi#4]
[https://forum.seeedstudio.com/t/wio-rp2040-mini-dev-board-please-provide-complete-api-or-repo/262961](https://forum.seeedstudio.com/t/wio-rp2040-mini-dev-board-please-provide-complete-api-or-repo/262961)
```
>>> import forum 
Traceback (most recent call last): 
  File "<stdin>", line 1, in <module> 
  File "forum.py", line 7, in <module> 
OSError: couldn't init nic esp8285 ,try again please 
 
>>>
```

**Comment by bgolab** [comment]
I see the same problem. Need to reconnect the USB cable to make it work.
